# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-04-26 09:50
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Doc',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('describe', models.CharField(max_length=3000)),
            ],
        ),
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.RemoveField(
            model_name='event',
            name='rate',
        ),
        migrations.AddField(
            model_name='project',
            name='category',
            field=models.CharField(choices=[('Sports', 'Спорт'), ('Art', 'Искусство'), ('Intel', 'Интеллектуальная деятельность')], default='M', max_length=30),
        ),
        migrations.AddField(
            model_name='project',
            name='describe',
            field=models.CharField(blank=True, max_length=6000),
        ),
        migrations.AddField(
            model_name='project',
            name='logo',
            field=models.CharField(blank=True, max_length=300),
        ),
        migrations.AddField(
            model_name='project',
            name='release_date',
            field=models.DateField(default=datetime.date(2016, 6, 25)),
        ),
        migrations.AddField(
            model_name='project',
            name='title',
            field=models.CharField(default='Unnamed', max_length=30),
        ),
        migrations.AddField(
            model_name='project',
            name='title_video',
            field=models.CharField(blank=True, max_length=300),
        ),
        migrations.AddField(
            model_name='image',
            name='project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='projects.Project'),
        ),
        migrations.AddField(
            model_name='doc',
            name='project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='projects.Project'),
        ),
    ]
