# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-04-29 10:21
from __future__ import unicode_literals

import datetime
import django.contrib.auth.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0007_alter_validators_add_error_messages'),
        ('projects', '0003_auto_20160427_2355'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='project',
            managers=[
                ('objects', django.contrib.auth.models.GroupManager()),
            ],
        ),
        migrations.RemoveField(
            model_name='project',
            name='id',
        ),
        migrations.RemoveField(
            model_name='project',
            name='project',
        ),
        migrations.AddField(
            model_name='project',
            name='group_ptr',
            field=models.OneToOneField(auto_created=True, default=0, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='auth.Group'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='project',
            name='release_date',
            field=models.DateField(default=datetime.date(2016, 6, 28)),
        ),
    ]
