# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-04-30 14:34
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0004_auto_20160429_1521'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='founder',
            field=models.CharField(blank=True, max_length=30),
        ),
        migrations.AlterField(
            model_name='project',
            name='release_date',
            field=models.DateField(default=datetime.date(2016, 6, 29)),
        ),
        migrations.AlterField(
            model_name='project',
            name='status',
            field=models.CharField(max_length=30),
        ),
    ]
