# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-05-01 06:02
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0005_auto_20160430_1934'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='rate',
            field=models.FileField(blank=True, max_length=300, upload_to=''),
        ),
        migrations.AlterField(
            model_name='project',
            name='category',
            field=models.CharField(choices=[('Sports', 'Спорт'), ('Art', 'Искусство'), ('Intel', 'Интеллектуальная деятельность')], default='Sport', max_length=30),
        ),
        migrations.AlterField(
            model_name='project',
            name='describe',
            field=models.CharField(default='Описание проекта одним абзацем', max_length=6000),
        ),
        migrations.AlterField(
            model_name='project',
            name='logo',
            field=models.ImageField(blank=True, max_length=300, null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='project',
            name='members',
            field=models.ManyToManyField(blank=True, through='projects.Membership', to='users.Student'),
        ),
        migrations.AlterField(
            model_name='project',
            name='release_date',
            field=models.DateField(default=datetime.date(2016, 6, 30)),
        ),
        migrations.AlterField(
            model_name='project',
            name='status',
            field=models.CharField(blank=True, max_length=30),
        ),
    ]
