# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-05-01 06:06
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0006_auto_20160501_1102'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='rate',
            field=models.CharField(blank=True, max_length=300),
        ),
    ]
