# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-05-02 18:38
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0007_auto_20160501_1106'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='image',
            name='project',
        ),
        migrations.AddField(
            model_name='doc',
            name='doc_src',
            field=models.FileField(default=1, max_length=300, upload_to=''),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='doc',
            name='describe',
            field=models.CharField(default=None, max_length=3000),
        ),
        migrations.AlterField(
            model_name='project',
            name='category',
            field=models.CharField(choices=[('Sports', 'Спорт'), ('Art', 'Искусство'), ('Intel', 'Интеллектуальная деятельность')], default='Sport', max_length=30, verbose_name='Категория'),
        ),
        migrations.AlterField(
            model_name='project',
            name='describe',
            field=models.CharField(default='Описание проекта одним абзацем', max_length=6000, verbose_name='Описание'),
        ),
        migrations.AlterField(
            model_name='project',
            name='founder',
            field=models.CharField(editable=False, max_length=30),
        ),
        migrations.AlterField(
            model_name='project',
            name='logo',
            field=models.ImageField(blank=True, max_length=300, null=True, upload_to='', verbose_name='Лого'),
        ),
        migrations.AlterField(
            model_name='project',
            name='release_date',
            field=models.DateField(default=datetime.date(2016, 7, 1)),
        ),
        migrations.AlterField(
            model_name='project',
            name='title',
            field=models.CharField(default='Unnamed', max_length=30, verbose_name='Заголовок'),
        ),
        migrations.AlterField(
            model_name='project',
            name='title_video',
            field=models.FileField(editable=False, max_length=300, upload_to='', verbose_name='Видео-презентация'),
        ),
        migrations.DeleteModel(
            name='Image',
        ),
    ]
