# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-05-12 10:24
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0008_auto_20160502_2338'),
    ]

    operations = [
        migrations.AlterField(
            model_name='doc',
            name='describe',
            field=models.CharField(blank=True, max_length=3000),
        ),
        migrations.AlterField(
            model_name='doc',
            name='project',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='projects.Project'),
        ),
        migrations.AlterField(
            model_name='event',
            name='date',
            field=models.DateField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='project',
            name='logo',
            field=models.ImageField(blank=True, default='default.jpg', max_length=300, null=True, upload_to='', verbose_name='Лого'),
        ),
        migrations.AlterField(
            model_name='project',
            name='release_date',
            field=models.DateField(default=datetime.date(2016, 7, 11)),
        ),
    ]
