# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-05-12 11:18
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0009_auto_20160510_1236'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='release_date',
            field=models.DateField(default=datetime.date(2016, 7, 11)),
        ),
    ]
