# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-05-12 15:37
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0009_auto_20160512_1524'),
    ]

    operations = [
        migrations.RenameField(
            model_name='membership',
            old_name='student',
            new_name='member',
        ),
        migrations.RemoveField(
            model_name='project',
            name='title_video',
        ),
        migrations.AddField(
            model_name='membership',
            name='registration_date',
            field=models.DateField(auto_now=True, default=datetime.datetime(2016, 5, 12, 15, 37, 25, 513839, tzinfo=utc)),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='membership',
            name='role',
            field=models.CharField(default='anchor', max_length=60),
        ),
        migrations.AddField(
            model_name='membership',
            name='status',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
