# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-05-13 20:50
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0010_auto_20160512_2037'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='founder',
        ),
        migrations.AlterField(
            model_name='project',
            name='release_date',
            field=models.DateField(default=datetime.date(2016, 7, 13)),
        ),
    ]
