# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-05-14 09:54
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0011_auto_20160514_0150'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='release_date',
            field=models.DateTimeField(default=datetime.date(2016, 5, 17)),
        ),
    ]
