# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-05-15 07:50
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0020_auto_20160515_1237'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='release_date',
            field=models.DateField(default=datetime.date(2016, 5, 18)),
        ),
    ]
