# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-05-15 09:25
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('users', '0005_auto_20160512_2037'),
        ('projects', '0021_auto_20160515_1250'),
    ]

    operations = [
        migrations.CreateModel(
            name='RelationToFeedback',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('member', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.Student')),
                ('vacancy', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='projects.Project')),
            ],
        ),
        migrations.CreateModel(
            name='Vacancy',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='', max_length=40, verbose_name='Заголовок вакансии')),
                ('text', models.CharField(default='', max_length=5000, verbose_name='Основной текст')),
                ('short_describe', models.CharField(default='', max_length=400, verbose_name='Краткое описание')),
                ('worker_position', models.CharField(default='', max_length=100, verbose_name='Кого ищем')),
                ('any_contact', models.CharField(default='', max_length=100, verbose_name='Контактная информация')),
                ('pub_date', models.DateField(auto_now_add=True)),
                ('project', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='projects.Project')),
            ],
        ),
    ]
