# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-05-02 18:38
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_auto_20160429_1521'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProjectMember',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(max_length=60)),
            ],
        ),
        migrations.AlterField(
            model_name='student',
            name='description',
            field=models.TextField(max_length=500, verbose_name='About you'),
        ),
        migrations.AddField(
            model_name='projectmember',
            name='account',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.Student'),
        ),
    ]
