# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-05-12 15:37
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_auto_20160502_2338'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='projectmember',
            name='account',
        ),
        migrations.DeleteModel(
            name='ProjectMember',
        ),
    ]
